name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - run: rustup update 1.70 --no-self-update && rustup default 1.70
    - run: cargo build --workspace --lib --bins --examples --tests
    - run: cargo test --workspace --lib --bins --examples --tests
    - run: rustup component add rustfmt
    - run: cargo fmt --check
    - run: cargo build --workspace --lib --bins --examples --tests --no-default-features
    - run: cargo test --workspace --lib --bins --examples --tests --no-default-features
